#!/usr/bin/env bash
set -euo pipefail

echo "# ── popup-service ──────────────────────────────────────────"
echo "ACCESS_TOKEN_SECRET=$(openssl rand -base64 48)"
echo "INVITE_TOKEN_SECRET=$(openssl rand -base64 48)"
echo "APPROVAL_TOKEN_SECRET=$(openssl rand -base64 48)"
echo "ADMIN_TOKEN=$(openssl rand -base64 32)"
echo "XMTP_DB_ENCRYPTION_KEY=$(openssl rand -hex 32)"
echo "BASE_URL=https://<popup-service>.up.railway.app"
echo ""
echo "# ── twitter-popup-connector ─────────────────────────────────"
echo "TX_BASE_URL=https://<twitter-connector>.up.railway.app"
echo "POPUP_SERVICE_URL=https://<popup-service>.up.railway.app  # must match popup-service BASE_URL"
echo "TWITTER_API_KEY=<your-twitter-api-key>"
echo "TWITTER_API_SECRET=<your-twitter-api-secret>"
echo "TWITTER_ACCESS_TOKEN=<your-twitter-access-token>"
echo "TWITTER_ACCESS_SECRET=<your-twitter-access-secret>"
echo "TWITTER_BOT_USERNAME=<your-bot-username>"
echo "TWITTER_OAUTH_CLIENT_ID=<your-oauth-client-id>"
echo "TWITTER_OAUTH_CLIENT_SECRET=<your-oauth-client-secret>"
echo "OPENAI_API_KEY=<your-openai-api-key>"
echo "TX_NAMESPACE=x-twitter"
echo "TX_DISPLAY_NAME=X (Twitter) Connector"
echo "TX_CONTACT_EMAIL=<your-contact-email>"
echo ""
echo "Copy popup-service vars into Railway Dashboard > popup-service > Variables"
echo "Copy twitter-connector vars into Railway Dashboard > twitter-connector > Variables"
